version: '2'

services:
  mysql:
    build: ./Database
    environment:
      - MYSQL_ROOT_PASSWORD=w5X4Hyi1NOF502y
      - MYSQL_USER=spurt
      - MYSQL_PASSWORD=nrYv7L1v5Nv5f6D
      - MYSQL_DATABASE=spurt

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
     - PMA_HOST=mysql
     - MYSQL_ROOT_PASSWORD=w5X4Hyi1NOF502y
     - VIRTUAL_HOST=mysql.spurt.dev
    links:
     - mysql

  service:
    build: ./Service/
    links:
      - mysql
    volumes:
      - "./Service:/app"
    environment:
     - VIRTUAL_HOST=spurt.dev
     - MYSQL_PORT=tcp://mysql:3306
     - MYSQL_USER=spurt
     - MYSQL_PASSWORD=nrYv7L1v5Nv5f6D
     - MYSQL_DATABASE=spurt
     - REDIS_PORT=tcp://redis:6379

  haproxy:
    image: 'dockercloud/haproxy:latest'
    environment:
      - 'STATS_AUTH=stats:CaptainMorgan'
      - TIMEOUT=connect 50000, client 500000, server 500000
    links:
      - service
      - phpmyadmin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.10.1:80:80'
      - '127.0.10.1:1936:1936'
